### ISSUE TITLE
readme implies lower than 5.7 support

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/announce#2]
yet https://github.com/mt-mods/announce/blob/5b601270ea13149ae61841cfcb93808fb5e2a044/announce.lua#L68-L69 isnt checked that it exists or not

**Comment by wsor4035** [comment]
pr that added it https://github.com/minetest/minetest/pull/12989

**Comment by BuckarooBanzay** [comment]
thanks for reporting :+1:
