### ISSUE TITLE
user reports that they need to use secure.trusted_mods setting rather than secure.http_mods to get it to work

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/announce#3]
see title, sees more of an engine thing than this mod thing, but creating an issue for now at least.....

**Comment by wsor4035** [comment]
docs do state both should work https://github.com/minetest/minetest/blob/master/doc/lua_api.md?plain=1#L6657-L6659 🤷

**Comment by BuckarooBanzay** [comment]
can't reproduce with `5.7.0` (using this myself here: https://github.com/BuckarooBanzay/supersam.minetest.ch/blob/5e7230b09df247591c95d7f7a199c457a60d48ff/minetest.conf#L21 and on another server without issues)

closing until i have additional infos (@NayiemWillems any pointers?)

**Comment by NayiemW** [comment]
No pointers. Other than that I'm using 5.6.0-dev.
